package com.luxzera.server.auth.entity;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_SET,
    SESSION_CREATED,
    SESSION_REVOKED,
    ALL_SESSIONS_REVOKED,
    EMAIL_VERIFIED,
    OTP_GENERATED,
    OTP_VERIFIED,
    OTP_FAILED,
    RATE_LIMIT_EXCEEDED
}
