"""Constants and versioning for Multimodal Fusion (Phase U6)."""

FUSION_VERSION = "v1"
REPRESENTATION_VERSION = "v1"
EMBEDDING_VERSION = "v1"

# Vector dimensionalities
DATA_VECTOR_DIMENSION = 86
VISUAL_VECTOR_DIMENSION = 512
BEHAVIOURAL_VECTOR_DIMENSION = 64
UNIFIED_VECTOR_DIMENSION = DATA_VECTOR_DIMENSION + VISUAL_VECTOR_DIMENSION + BEHAVIOURAL_VECTOR_DIMENSION  # 662

# Modality weights (guided by source availability)
DEFAULT_DATA_WEIGHT = 0.40
DEFAULT_VISUAL_WEIGHT = 0.35
DEFAULT_BEHAVIOURAL_WEIGHT = 0.25
