import datetime
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field, ConfigDict

from zyra.zyra_model.config.constants import DEFAULT_RECOMMENDATION_LIMIT, ZYRA_MODEL_VERSION
from zyra.zyra_model.models.ranking.ranker import RankedCandidate, RankedCandidateSet
from zyra.zyra_model.recommendation.exceptions import InvalidUserInputException


class ScoreBreakdown(BaseModel):
    """Component score breakdown for recommendation explainability and debugging."""

    model_config = ConfigDict(populate_by_name=True)

    retrieval_score: float = Field(..., alias="retrievalScore", ge=0.0, le=1.0)
    person_garment_score: float = Field(..., alias="personGarmentScore", ge=0.0, le=1.0)
    outfit_compatibility_score: float = Field(..., alias="outfitCompatibilityScore", ge=0.0, le=1.0)
    occasion_score: float = Field(..., alias="occasionScore", ge=0.0, le=1.0)


class RecommendationItem(BaseModel):
    """Final personalized product recommendation item."""

    model_config = ConfigDict(
        populate_by_name=True,
        extra="ignore",
    )

    product_id: str = Field(..., alias="productId", min_length=1)
    rank: int = Field(..., ge=1, description="Assigned recommendation rank (1 to limit)")
    final_suitability_score: float = Field(
        ...,
        alias="finalSuitabilityScore",
        ge=0.0,
        le=1.0,
        description="Synthesized recommendation score in [0.0, 1.0]",
    )
    retrieval_score: float = Field(..., alias="retrievalScore", ge=0.0, le=1.0)
    person_garment_score: float = Field(..., alias="personGarmentScore", ge=0.0, le=1.0)
    outfit_compatibility_score: float = Field(..., alias="outfitCompatibilityScore", ge=0.0, le=1.0)
    occasion_score: float = Field(..., alias="occasionScore", ge=0.0, le=1.0)
    score_breakdown: ScoreBreakdown = Field(..., alias="scoreBreakdown")
    product_profile: Optional[Dict[str, Any]] = Field(default_factory=dict, alias="productProfile")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ZyraRecommendationResponse(BaseModel):
    """Complete recommendation response for a specific occasion."""

    model_config = ConfigDict(populate_by_name=True)

    user_id: str = Field(..., alias="userId")
    occasion: str = Field(..., description="The occasion for which recommendations were generated")
    total_recommendations: int = Field(..., alias="totalRecommendations", ge=0)
    recommendations: List[RecommendationItem] = Field(default_factory=list)
    generated_at: str = Field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat(),
        alias="generatedAt",
    )
    version: str = Field(default=ZYRA_MODEL_VERSION)


class ZyraMultiOccasionRecommendationResponse(BaseModel):
    """Multi-occasion recommendation response containing separate Top-K sets per requested occasion."""

    model_config = ConfigDict(populate_by_name=True)

    user_id: str = Field(..., alias="userId")
    recommendations: Dict[str, List[RecommendationItem]] = Field(
        default_factory=dict,
        description="Map of occasion name to its independent ranked recommendation list",
    )
    total_occasions: int = Field(..., alias="totalOccasions", ge=0)
    generated_at: str = Field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat(),
        alias="generatedAt",
    )
    version: str = Field(default=ZYRA_MODEL_VERSION)


class Top10RecommendationGenerator:
    """
    Top-K Recommendation Generator (Phase ZM-8).
    
    Responsibility:
    - Selects the final Top-K recommendations (default 10) from the ranked candidates produced by ZM-7.
    - Validates 1 <= limit <= 50.
    - Preserves exact ranks, scores, and component attribution generated by ZM-7.
    - Does NOT re-score or invent recommendations if fewer candidates are available.
    """

    def __init__(self, default_limit: int = DEFAULT_RECOMMENDATION_LIMIT) -> None:
        self.default_limit = default_limit

    def generate(
        self,
        ranked_candidates: Union[RankedCandidateSet, List[RankedCandidate], List[Dict[str, Any]]],
        user_id: Optional[str] = None,
        occasion: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> ZyraRecommendationResponse:
        """
        Extract top recommendations up to requested limit.
        """
        k = limit if limit is not None else self.default_limit

        # Validate limit bounds
        if not isinstance(k, int) or k < 1 or k > 50:
            raise InvalidUserInputException(
                f"Recommendation limit must be an integer between 1 and 50 (got {k})",
                details={"limit": k, "min_limit": 1, "max_limit": 50},
            )

        # Unpack candidates list
        items: List[RankedCandidate] = []
        eff_user_id = user_id or "anonymous_user"
        eff_occasion = occasion or "general"

        if isinstance(ranked_candidates, RankedCandidateSet):
            items = ranked_candidates.items
            if ranked_candidates.user_id:
                eff_user_id = ranked_candidates.user_id
            if ranked_candidates.occasion:
                eff_occasion = ranked_candidates.occasion
        elif isinstance(ranked_candidates, list):
            for entry in ranked_candidates:
                if isinstance(entry, RankedCandidate):
                    items.append(entry)
                elif isinstance(entry, dict):
                    items.append(RankedCandidate(**entry))
                else:
                    raise InvalidUserInputException(f"Unsupported candidate item type: {type(entry)}")

        # Select Top-K unique candidates (deduplicating by title, ID, and image)
        seen_titles = set()
        seen_ids = set()
        seen_images = set()
        selected_candidates: List[RankedCandidate] = []

        for cand in items:
            pid = str(cand.product_id).strip()
            prof = cand.product_profile or {}
            title = str(prof.get("title") or cand.metadata.get("title") or pid).strip().lower()
            img = str(prof.get("imageUrl") or prof.get("image") or cand.metadata.get("image") or "").strip()

            if pid in seen_ids:
                continue
            if title and title in seen_titles:
                continue
            if img and img in seen_images:
                continue

            seen_ids.add(pid)
            if title:
                seen_titles.add(title)
            if img:
                seen_images.add(img)

            selected_candidates.append(cand)
            if len(selected_candidates) >= k:
                break

        # Fallback: if deduplication resulted in fewer than k and candidates remain, backfill
        if len(selected_candidates) < k:
            for cand in items:
                if cand.product_id not in seen_ids:
                    seen_ids.add(cand.product_id)
                    selected_candidates.append(cand)
                    if len(selected_candidates) >= k:
                        break

        # Convert to RecommendationItem list with sequential 1-indexed ranks
        recommendations: List[RecommendationItem] = []
        for idx, cand in enumerate(selected_candidates, start=1):
            breakdown = ScoreBreakdown(
                retrieval_score=cand.retrieval_score,
                person_garment_score=cand.person_garment_score,
                outfit_compatibility_score=cand.outfit_compatibility_score,
                occasion_score=cand.occasion_score,
            )
            rec_item = RecommendationItem(
                product_id=cand.product_id,
                rank=idx,
                final_suitability_score=cand.final_suitability_score,
                retrieval_score=cand.retrieval_score,
                person_garment_score=cand.person_garment_score,
                outfit_compatibility_score=cand.outfit_compatibility_score,
                occasion_score=cand.occasion_score,
                score_breakdown=breakdown,
                product_profile=cand.product_profile,
                metadata=cand.metadata,
            )
            recommendations.append(rec_item)

        return ZyraRecommendationResponse(
            user_id=eff_user_id,
            occasion=eff_occasion,
            total_recommendations=len(recommendations),
            recommendations=recommendations,
            version=ZYRA_MODEL_VERSION,
        )
