package com.luxzera.server.admin.enums;

public enum AdminSecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    OTP_SENT,
    OTP_FAILED,
    OTP_EXPIRED,
    OTP_LOCKED,
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_REVOKED,
    ACCOUNT_LOCKED,
    SESSION_CREATED,
    SESSION_REVOKED,
    LOGOUT,
    SUPER_ADMIN_BOOTSTRAP,
    PERMISSION_DENIED,
    PRIVILEGE_ESCALATION_ATTEMPT,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    ADMIN_MUTATION
}
