from .events import UserProfileUpdatedEvent
from .springboot_dto import (
    SpringBootUserEncoderResponse,
    SpringBootGeneralProfileDto,
    SpringBootFitDataDto,
    SpringBootRecommendationImageDto,
)
from .input_schema import (
    UserEncoderInput,
    GeneralProfileInput,
    UserFitDataInput,
    RecommendationImageInput,
)
from .encoder_inputs import (
    ImageEncoderInput,
    DataEncoderInput,
    BehaviourEncoderInput,
    UserEncoderPipelineInput,
)
from .image_encoder_schemas import (
    ImageEncoderOutput,
    UserVisualInsights,
    VisualRepresentation,
    ImageAnalysisResult,
    PoseLandmarkInsights,
    GarmentSegmentationInsights,
    ImageStyleInsights,
    ImageColorInsights,
)
from .data_encoder_schemas import (
    DataEncoderOutput,
    StructuredFashionInsights,
    DataRepresentation,
    PhysicalFitInsights,
    StyleIdentityInsights,
    ClothingPreferenceInsights,
    ColorPreferenceInsights,
    OccasionProfileInsights,
    BudgetProfileInsights,
    ShoppingPriorityInsights,
    FashionGoalInsights,
    PreferenceConflict,
    SourceTrace,
)

from .behaviour_encoder_schemas import (
    BehaviourEncoderOutput,
    BehaviourInsights,
    BehaviourRepresentation,
    BehaviourEvent,
    CategoryInterest,
    BrandAffinity,
    StyleInteractionSignal,
    ColorInteractionSignal,
    PriceBehaviourSummary,
    BehaviouralConflict,
    EventSummary,
)

from .unified_insight_schemas import (
    SourceAwareInsight,
    UnifiedFashionIdentity,
    UnifiedStyleInsights,
    UnifiedClothingInsights,
    UnifiedColorInsights,
    UnifiedFitInsights,
    UnifiedOccasionInsights,
    UnifiedBudgetInsights,
    UnifiedShoppingPriorityInsights,
    UnifiedFashionGoalInsights,
    UnifiedConflict,
    SourceSummary,
    EncoderVersionManifest,
    InsightAggregationInput,
    UnifiedUserInsights,
)

from .fusion_schemas import (
    ModalityPresence,
    UnifiedUserRepresentation,
    UserEmbedding,
    FusionOutput,
)

from .persistence_schemas import (
    EmbeddingReference,
    UserZyraRepresentationEntity,
    UserZyraRepresentationResponse,
    UserRecommendationEntity,
    UserRecommendationsResponse,
)

__all__ = [
    "UserProfileUpdatedEvent",
    "SpringBootUserEncoderResponse",
    "SpringBootGeneralProfileDto",
    "SpringBootFitDataDto",
    "SpringBootRecommendationImageDto",
    "UserEncoderInput",
    "GeneralProfileInput",
    "UserFitDataInput",
    "RecommendationImageInput",
    "ImageEncoderInput",
    "DataEncoderInput",
    "BehaviourEncoderInput",
    "UserEncoderPipelineInput",
    "ImageEncoderOutput",
    "UserVisualInsights",
    "VisualRepresentation",
    "ImageAnalysisResult",
    "PoseLandmarkInsights",
    "GarmentSegmentationInsights",
    "ImageStyleInsights",
    "ImageColorInsights",
    "DataEncoderOutput",
    "StructuredFashionInsights",
    "DataRepresentation",
    "PhysicalFitInsights",
    "StyleIdentityInsights",
    "ClothingPreferenceInsights",
    "ColorPreferenceInsights",
    "OccasionProfileInsights",
    "BudgetProfileInsights",
    "ShoppingPriorityInsights",
    "FashionGoalInsights",
    "PreferenceConflict",
    "SourceTrace",
    "BehaviourEncoderOutput",
    "BehaviourInsights",
    "BehaviourRepresentation",
    "BehaviourEvent",
    "CategoryInterest",
    "BrandAffinity",
    "StyleInteractionSignal",
    "ColorInteractionSignal",
    "PriceBehaviourSummary",
    "BehaviouralConflict",
    "EventSummary",
    "SourceAwareInsight",
    "UnifiedFashionIdentity",
    "UnifiedStyleInsights",
    "UnifiedClothingInsights",
    "UnifiedColorInsights",
    "UnifiedFitInsights",
    "UnifiedOccasionInsights",
    "UnifiedBudgetInsights",
    "UnifiedShoppingPriorityInsights",
    "UnifiedFashionGoalInsights",
    "UnifiedConflict",
    "SourceSummary",
    "EncoderVersionManifest",
    "InsightAggregationInput",
    "UnifiedUserInsights",
    "ModalityPresence",
    "UnifiedUserRepresentation",
    "UserEmbedding",
    "FusionOutput",
    "EmbeddingReference",
    "UserZyraRepresentationEntity",
    "UserZyraRepresentationResponse",
    "UserRecommendationEntity",
    "UserRecommendationsResponse",
]
